[log]
level = "debug"
destination = "stdout"
filename = "server.log"

[infrastructure.httpServer]
port = "8080"
corsAllowAll = true
timeout = "10s"

[infrastructure.mongoDB]
host = "localhost:27017"
timeout = "10s"

[settings]
usersFilename = "users.yml"
authCacheExpiration = "1m"
cpuReadDuration = "1s"
